"""Offline, no API key. Drives the REAL agent code with a scripted AI, so every failure path can be
seen on demand. Writes results/blockers-demo.md.   Run: python scripts/demo_blockers.py"""
import json
import tempfile
from pathlib import Path

from common import ROOT  # noqa: F401  (sets up the import path)
from nextstep.agent import NextStepAgent
from nextstep.clock import FakeClock
from nextstep.faults import Faults
from nextstep.model import ScriptedModel, fake_reply, text, tool
from nextstep.store import SituationStore
from nextstep.tools.messages import MockOutbox
from nextstep.tools.situation import update_situation
from nextstep.tools.tasks import retry_failed_tasks
from nextstep.views import tasks

md = ["# Safety checks demo (offline, scripted AI, real agent code)", "", "Generated by `python scripts/demo_blockers.py`. Only the AI is scripted; everything else is the real code.", ""]


def log(s: str = "") -> None:
    md.append(s)
    print(s)


ASSESS = fake_reply([{"type": "tool_use", "name": "recordAssessment", "input": {
    "language": "English", "request_type": "situation_help", "risk_level": "none", "risk_signals": [],
    "problems": [{"id": "p1", "title": "Partner unresponsive before viva", "category": "academic", "urgency": "high", "deadline_text": "10am tomorrow", "facts": []}],
    "contradictions": [], "missing_info": [], "untrusted_instructions_seen": [],
    "top_priority": {"problem_id": "p1", "next_action": "message partner", "why": "viva tomorrow"}}}])


def setup(turns):
    d = Path(tempfile.mkdtemp(prefix="nextstep-demo-"))
    clock = FakeClock("2026-09-26T21:00:00+05:30")
    store = SituationStore(d, clock)
    faults, outbox = Faults(), MockOutbox(d)
    return clock, store, faults, outbox, NextStepAgent(store, ScriptedModel(turns), outbox, faults)


def draft_then_send():
    def send(req):
        return tool("sendMessage", {"draft_id": json.loads(req["messages"][-1]["content"][0]["content"])["draftId"]})
    return [ASSESS, tool("draftMessage", {"recipient": "Rohan (project partner)", "channel": "whatsapp", "body": "Hey Rohan, viva is at 10am tomorrow. Can you send me your slides tonight? Just need them by 9pm.", "purpose": "get slides before viva"}),
            send, text("I've drafted a message to Rohan. Please check it before it goes.")]


log("## 1. Never send twice + 5. exact-text confirmation")
clock, store, faults, outbox, agent = setup(draft_then_send())
r = agent.start("Viva at 10am tomorrow, partner not replying")
p = r["pendingActions"][0]
sid, aid = r["situationId"], p["actionId"]
log(f"- run status: `{r['status']}`; outbox has {len(outbox.all())} message(s) (proposing sends nothing)")
log("- exact text shown to the user:")
log("```text\n" + p["exactText"] + "\n```")
log(f"- send before the user says yes -> `{agent.actions.execute(sid, aid)['status']}`")
log(f"- yes with edited text -> ok={agent.actions.confirm(sid, aid, p['exactText'] + ' ')['ok']}")
log(f"- yes with the exact text -> ok={agent.actions.confirm(sid, aid, p['exactText'])['ok']}")
faults.fail_next_send("fail_after_delivery")
log(f"- attempt 1 (network dies after delivery): `{agent.actions.execute(sid, aid)['status']}`; outbox now has {len(outbox.all())}")
a2 = agent.actions.execute(sid, aid)
log(f"- user taps retry: `{a2['status']}`" + (" (found in the outbox by its fingerprint, NOT sent again)" if a2.get("reconciled") else ""))
log(f"- user taps retry again: `{agent.actions.execute(sid, aid)['status']}`")
log(f"- **outbox total: {len(outbox.all())}** (delivered exactly once)")
log("")

log("## 2. Staleness recheck")
clock, store, faults, outbox, agent = setup(draft_then_send())
r = agent.start("Viva at 10am tomorrow, partner not replying")
p = r["pendingActions"][0]
agent.actions.confirm(r["situationId"], p["actionId"], p["exactText"])
log(f"- user says yes at {clock.now().isoformat()}")
clock.advance_minutes(10)
update_situation(store, r["situationId"], "Rohan replied: 'sending slides in 5 min, sorry, phone was dead'", "inbound")
log("- 10 minutes later Rohan replies (situation v1 -> v2)")
ex = agent.actions.execute(r["situationId"], p["actionId"])
log(f"- send -> `{ex['status']}` ({ex.get('reason')}); outbox: {len(outbox.all())}")
log(f"- shown to user: {' | '.join(ex.get('changes', []))}")
log("")

log("## 3. Step budget")
clock, store, faults, outbox, agent = setup([ASSESS] + [tool("searchInformation", {"query": f"laptop repair near me {i}"}) for i in range(20)])
r = agent.start("laptop won't boot")
log(f"- scripted AI asks for 20 searches; run status `{r['status']}`, tool calls used {r['budget']['toolCallsUsed']}/{r['budget']['maxToolCalls']}")
log(f"- real searches run: {sum(1 for s in r['trace'] if s['kind'] == 'searchInformation_stub')} (per-run search limit)")
log("- reply:")
log("```text\n" + r["response"] + "\n```")
log("")

log("## 4. Partial failure")
five = [{"title": t} for t in ["Call mom for update on dad", "Email viva coordinator", "Borrow a laptop from Neha", "Recover project from Drive", "Check buses to Surat"]]
clock, store, faults, outbox, agent = setup([ASSESS, tool("createTask", {"tasks": five}), text("ok")])
faults.fail_task_at(3)
r = agent.start("multi problem")
b = next(s for s in r["trace"] if s["kind"] == "createTask_partial_failure")["detail"]
log("- succeeded: " + "; ".join(x["title"] for x in b["succeeded"]))
log("- failed: " + "; ".join(f"{x['title']} ({x['error']})" for x in b["failed"]))
log("- not tried: " + "; ".join(x["title"] for x in b["remaining"]))
log("- what the user is told: " + " ".join(r["notices"]))
retry = retry_failed_tasks(store, r["situationId"], b["batchId"], faults, "Asia/Kolkata")
log(f"- retry -> `{retry['status']}`; {sum(1 for s in retry['succeeded'] if not s.get('alreadyExisted'))} created now, "
    f"{sum(1 for s in retry['succeeded'] if s.get('alreadyExisted'))} already existed; total tasks: {len(tasks(store, r['situationId']))}")
log("")

log("## 7. Harmful requests (refused before the AI is even called)")
for req in ["Draft a fake medical excuse for my professor.", "Message my ex until she replies."]:
    *_, agent = setup([ASSESS, text("should never be reached")])
    r = agent.start(req)
    log(f'- "{req}" -> `{r["status"]}`: ' + r["response"].replace("\n", " "))
log("")

(Path(__file__).resolve().parent.parent / "results" / "blockers-demo.md").write_text("\n".join(md) + "\n", encoding="utf-8")
print("\nSaved results/blockers-demo.md")
